export { default as api } from './api.routes.js';
export { default as auth } from './auth.routes.js';
export { default as dashboard } from './dashboard.routes.js';
export { default as integrations } from './integrations.routes.js';
export { default as inventory } from './inventory.routes.js';
export { default as schedule } from './schedule.routes.js';
export { default as supplements } from './supplements.routes.js';
export { default as test } from './test.routes.js';
export { default as users } from './users.routes.js';
