export type Theme =
  | 'white'
  | 'primary'
  | 'secondary'
  | 'success'
  | 'gray'
  | 'success-bright'
  | 'accent-pink'
  | 'accent-purple'
  | 'accent-magenta'
  | 'warning'
  | 'danger'
  | 'info'
  | 'gradient-primary'
  | 'gradient-secondary';
